### ISSUE TITLE
Add translations to meanings

### ISSUE THREAD

**Issue by kompot** [BenediktGeiger/sonad-api#20]
I was thinking about using SõnAPI to create my own Anki flash cards based on some text input and basically the only thing I'm missing is translation to another language of a meaning.

So My proposal is that given https://api.sonapi.ee/v2/masin and https://sonaveeb.ee/search/unif/dlall/dsall/masin/1 add `translations` node to within meaning

so that 
```
{
          "definition": "seade või seadmete kogum, mille tööosad talitlevad kooskõlas, et sooritada energia, tööobjektide või informatsiooni muundamiseks vajalikke liikumisi,mis tahes seade, nt pesu- või kohvimasin,liikuvate osadega seade, mille eesmärk on teha inimese tööd kergemaks",
          "partOfSpeech": [
            {
              "code": "s",
              "value": "nimisõna, substantiiv"
            }
          ],
          "examples": [
            "Pessimistid arvavad, et masinad võtavad inimestelt töö ära.",
...
            "Tehase masinad läksid rikki."
          ],
          "synonyms": [
            "seade",
            "automaat",
            ...
            "riist",
            "majapidamisriist"
          ]
        }
```

will have an additional node like this

```
  "translations": {
    "fr": ["machine"],
    "ru": ["машина", "машинка", "станок"],
    "uk": ["машина", "машинка", "верстат"]
  }
```

I don't understand why they don't have english there (almost?) never but still this would be very useful.

Thanks!

**Comment by BenediktGeiger** [comment]
@kompot 
sorry for the late reply.
I am actually not web scraping sonaveeb anymore. I am using the ekilex api under the hood
https://github.com/keeleinstituut/ekilex/wiki/Ekilex-API

I would need to check if they provide the same translations as you can see in sonaveeb.

My english estonian translations are actually coming from a database from the eesti keele institut which I have locally in a sql database stored. 
So for the translations I am not using any kind of information from sonaveeb or ekilex. 
The idea itself seems very cool. Not sure how much resources I can put into it given the fact that this is just a hobby project

**Comment by kompot** [comment]
Thanks for your reply. Totally understand that it's a pet project. I've just found myself in a situation where really often I check my native (Russian) translation and it's often more likely to be present on Sonaveeb than an English one. If you ever decide to tackle this task I'm ready to help with testing at least. Cheers!

**Comment by BenediktGeiger** [comment]
@kompot 
I finally had some time adding the translations :) 

Every "meaning" has now a translation part. 
I also added a `weight` param which indicates which translation is the most suitable one. 1 being the most suitable one.
I hope that helps

```
{
    "requestedWord": "mees",
    "estonianWord": "mees",
    "searchResult": [
        {
            "wordClasses": ["noomen"],
            "wordForms": [...],
            "meanings": [
                {
                    "definition": "(hrl täiskasvanud) meessoost inimene,täiskasvanud meessoost inimene",
                    "partOfSpeech": [...],
                    "examples": [...],
                    "synonyms": [...],
                    "translations": {
                        "fra": [
                            {"words": "homme","weight": 1},
                            {"words": "monsieur","weight": 0.7}
                        ],
                        "rus": [
                            {"words": "мужчина","weight": 1},
                            {"words": "мужик","weight": 1},
                            {"words": "мужчина","weight": 0.9},
                            {"words": "самец","weight": 0.9},
                            {"words": "брат,дружочек,дружище,братец,голубчик,братан,браток,дружок,малый,братишка,братик","weight": 0.7},
                            {"words": "сын,муж","weight": 0.8067}
                        ],
                        "ukr": [
                            {"words": "чоловік","weight": 1},
                            {"words": "пан,добродій","weight": 0.7}
                        ],
                        "eng": [
                            {"words": "gentleman,mister","weight": 0.7}
                        ]
                    }
                }
            ]
        }
    ]
}
```

**Comment by kompot** [comment]
Love it, weight would be definitely helpful to render lower weight translation with opacity in cards.  Will try to compose set of Anki cards. Thanks!
